name: Self-hosted CI

on:
  pull_request:
    branches: [ master, develop ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:


jobs:

 ########################################################################################
  checkout:
    name: checkout
    runs-on: [self-hosted, famsa]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: copy sl->mp references
      run: |
        cp ./test/adeno_fiber/sl.fasta ./test/adeno_fiber/mp.fasta
        cp ./test/hemopexin/medoid-sl.fasta ./test/hemopexin/medoid-mp.fasta
      
          
  ########################################################################################
  make-tests:
    name: make
    runs-on: [self-hosted, famsa]
    needs: checkout
    strategy:
      fail-fast: false
      matrix:
        compiler: [9, 10, 11]
        
    steps:
    - name: make (g++-${{matrix.compiler}})
      run: | 
        make -j32 CXX=g++-${{matrix.compiler}}
        cp ./famsa ./famsa-${{matrix.compiler}}
        make clean
        
  ########################################################################################
  noavx-tests:
    name: no AVX extensions
    runs-on: [self-hosted, famsa]
    needs: make-tests
    strategy:
      fail-fast: false
      matrix:
        compiler: [9, 10, 11]
        cpu_ext: [none32, none64, sse4, avx1]
        
    env: 
      REF_DIR: ./test/adeno_fiber
      INPUT: ./test/adeno_fiber/adeno_fiber
        
    steps:
    - name: clean
      run: make clean
    - name: make (g++-${{matrix.compiler}}, CPU extension ${{matrix.cpu_ext}})
      run: | 
        make -j32 CXX=g++-${{matrix.compiler}} CPU_EXT=${{matrix.cpu_ext}}
    - name: distance calculation
      run: |
        ./famsa -dist_export ${INPUT} dist.csv
        cmp dist.csv ${REF_DIR}/dist.csv 
      
  ########################################################################################    
    
  full-tree:
    name: adeno-fiber - full tree
    runs-on: [self-hosted, famsa]
    needs: noavx-tests
    strategy:
      fail-fast: false
      matrix:
        compiler: [9, 10, 11]
        tree: [sl, upgma, mp]
        
    env: 
      REF_DIR: ./test/adeno_fiber
      INPUT: ./test/adeno_fiber/adeno_fiber
 
    steps:  

    - name: ${{matrix.tree}} (tree only)
      run: |
        ./famsa-${{matrix.compiler}} -gt ${{matrix.tree}} -gt_export ${INPUT} ${{matrix.tree}}.dnd
        cmp ${{matrix.tree}}.dnd ${REF_DIR}/${{matrix.tree}}.dnd
    
    - name: ${{matrix.tree}} (complete alignment)
      run: |
        ./famsa-${{matrix.compiler}} -gt ${{matrix.tree}} ${INPUT} ${{matrix.tree}}.fasta
        cmp ${{matrix.tree}}.fasta ${REF_DIR}/${{matrix.tree}}.fasta
     
    - name: ${{matrix.tree}} (from tree)
      run: |
        ./famsa-${{matrix.compiler}} -gt import ${{matrix.tree}}.dnd ${INPUT} ${{matrix.tree}}.dnd.fasta
        cmp ${{matrix.tree}}.dnd.fasta ${REF_DIR}/${{matrix.tree}}.fasta
        
    - name: ${{matrix.tree}} (gzip)
      run: |
        ./famsa-${{matrix.compiler}} -gz -gt ${{matrix.tree}} ${INPUT} ${{matrix.tree}}.fasta.gz
        pigz -f -d ${{matrix.tree}}.fasta.gz
        cmp ${{matrix.tree}}.fasta ${REF_DIR}/${{matrix.tree}}.fasta
        
 ########################################################################################    
    
  medoid-tree:
    name: hemopexin - medoid tree
    runs-on: [self-hosted, famsa]
    needs: full-tree
    strategy:
      fail-fast: false
      matrix:
        compiler: [9, 10, 11]
        tree: [sl, upgma, mp, nj]
        
    env: 
      REF_DIR: ./test/hemopexin
      INPUT: ./test/hemopexin/hemopexin
 
    steps:  

    - name: medoid + ${{matrix.tree}}  (tree only)
      run: |
        ./famsa-${{matrix.compiler}} -medoidtree -gt ${{matrix.tree}} -gt_export ${INPUT} medoid-${{matrix.tree}}.dnd
        cmp  medoid-${{matrix.tree}}.dnd ${REF_DIR}/medoid-${{matrix.tree}}.dnd
    
    - name: medoid + ${{matrix.tree}}  (complete alignment)
      run: |
        ./famsa-${{matrix.compiler}} -medoidtree -gt ${{matrix.tree}} ${INPUT} medoid-${{matrix.tree}}.fasta
        cmp medoid-${{matrix.tree}}.fasta ${REF_DIR}/medoid-${{matrix.tree}}.fasta
     
    - name: medoid + ${{matrix.tree}}  (from tree)
      run: |
        ./famsa-${{matrix.compiler}} -gt import medoid-${{matrix.tree}}.dnd ${INPUT} medoid-${{matrix.tree}}.dnd.fasta
        cmp medoid-${{matrix.tree}}.dnd.fasta ${REF_DIR}/medoid-${{matrix.tree}}.fasta
        
    - name: medoid + ${{matrix.tree}}  (non-default params)
      run: |
        ./famsa-${{matrix.compiler}} -medoidtree -gt ${{matrix.tree}} -gt_export -subtree_size 10 -sample_size 100 -cluster_fraction 0.2 -cluster_iters 1 ${INPUT} medoid-${{matrix.tree}}-params.dnd
        cmp  medoid-${{matrix.tree}}-params.dnd ${REF_DIR}/medoid-${{matrix.tree}}-params.dnd
        
  ########################################################################################        
         
  other-tests:
    name: adeno-fiber - other tests
    runs-on: [self-hosted, famsa]
    needs: medoid-tree
    strategy:
      fail-fast: false
      matrix:
        compiler: [9, 10, 11]
        
    env: 
      REF_DIR: ./test/adeno_fiber
      INPUT: ./test/adeno_fiber/adeno_fiber
     
    steps:
    
    - name: non-default gaps
      run: |
        ./famsa-${{matrix.compiler}} -go 10 -ge 2 -tgo 0.5 -tge 1.0 -gsd 3 -gsl 30 ${INPUT} gaps.fasta
        cmp gaps.fasta ${REF_DIR}/gaps.fasta
    
    - name: export distance
      run: |
        ./famsa-${{matrix.compiler}} -dist_export ${INPUT} dist.csv
        cmp dist.csv ${REF_DIR}/dist.csv
        
    - name: export distance (square)
      run: |
        ./famsa-${{matrix.compiler}} -dist_export -square_matrix ${INPUT} dist_sq.csv
        cmp dist_sq.csv ${REF_DIR}/dist_sq.csv
        
    - name: export pid
      run: |
        ./famsa-${{matrix.compiler}} -dist_export -pid ${INPUT} pid.csv
        cmp pid.csv ${REF_DIR}/pid.csv
        
    - name: export pid (square)
      run: |
        ./famsa-${{matrix.compiler}} -dist_export -square_matrix -pid ${INPUT} pid_sq.csv
        cmp pid_sq.csv ${REF_DIR}/pid_sq.csv
      


