name: Self-hosted CI

on:
  pull_request:
    branches: [ master, develop ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:


jobs:

 ########################################################################################
  checkout:
    name: checkout
    runs-on: [self-hosted, famsa]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: copy sl->mp references
      run: |
        cp ./test/adeno_fiber/sl.fasta ./test/adeno_fiber/mp.fasta
        cp ./test/adeno_fiber/medoid-sl.fasta ./test/adeno_fiber/medoid-mp.fasta
      
          
  ########################################################################################
  make-tests:
    name: make
    runs-on: [self-hosted, famsa]
    needs: checkout
    strategy:
      fail-fast: false
      matrix:
        compiler: [9, 10, 11]
        
    steps:
    - name: make (g++-${{matrix.compiler}})
      run: | 
        make -j32 CXX=g++-${{matrix.compiler}}
        cp ./famsa ./famsa-${{matrix.compiler}}
        make clean
      
  ########################################################################################    
    
  full-tree:
    name: adeno-fiber - full tree
    runs-on: [self-hosted, famsa]
    needs: make-tests
    strategy:
      fail-fast: false
      matrix:
        compiler: [9, 10, 11]
        tree: [sl, upgma, mp]
        
    env: 
      REF_DIR: ./test/adeno_fiber
      INPUT: ./test/adeno_fiber/adeno_fiber
 
    steps:  

    - name: ${{matrix.tree}} (tree only)
      run: |
        ./famsa-${{matrix.compiler}} -gt ${{matrix.tree}} -gt_export ${INPUT} ${{matrix.tree}}.dnd
        cmp ${{matrix.tree}}.dnd ${REF_DIR}/${{matrix.tree}}.dnd
    
    - name: ${{matrix.tree}} (complete alignment)
      run: |
        ./famsa-${{matrix.compiler}} -gt ${{matrix.tree}} ${INPUT} ${{matrix.tree}}.fasta
        cmp ${{matrix.tree}}.fasta ${REF_DIR}/${{matrix.tree}}.fasta
     
    - name: ${{matrix.tree}} (from tree)
      run: |
        ./famsa-${{matrix.compiler}} -gt import ${{matrix.tree}}.dnd ${INPUT} ${{matrix.tree}}.dnd.fasta
        cmp ${{matrix.tree}}.dnd.fasta ${REF_DIR}/${{matrix.tree}}.fasta
        
    - name: ${{matrix.tree}} (gzip)
      run: |
        ./famsa-${{matrix.compiler}} -gz -gt ${{matrix.tree}} ${INPUT} ${{matrix.tree}}.fasta.gz
        pigz -f -d ${{matrix.tree}}.fasta.gz
        cmp ${{matrix.tree}}.fasta ${REF_DIR}/${{matrix.tree}}.fasta
        
 ########################################################################################    
    
  medoid-tree:
    name: adeno-fiber - medoid tree
    runs-on: [self-hosted, famsa]
    needs: full-tree
    strategy:
      fail-fast: false
      matrix:
        compiler: [9, 10, 11]
        tree: [sl, upgma, mp]
        
    env: 
      REF_DIR: ./test/adeno_fiber
      INPUT: ./test/adeno_fiber/adeno_fiber
 
    steps:  

    - name: medoid + ${{matrix.tree}}  (tree only)
      run: |
        ./famsa-${{matrix.compiler}} -medoidtree -gt ${{matrix.tree}} -gt_export ${INPUT} medoid-${{matrix.tree}}.dnd
        cmp  medoid-${{matrix.tree}}.dnd ${REF_DIR}/medoid-${{matrix.tree}}.dnd
    
    - name: medoid + ${{matrix.tree}}  (complete alignment)
      run: |
        ./famsa-${{matrix.compiler}} -medoidtree -gt ${{matrix.tree}} ${INPUT} medoid-${{matrix.tree}}.fasta
        cmp medoid-${{matrix.tree}}.fasta ${REF_DIR}/medoid-${{matrix.tree}}.fasta
     
    - name: medoid + ${{matrix.tree}}  (from tree)
      run: |
        ./famsa-${{matrix.compiler}} -gt import medoid-${{matrix.tree}}.dnd ${INPUT} medoid-${{matrix.tree}}.dnd.fasta
        cmp medoid-${{matrix.tree}}.dnd.fasta ${REF_DIR}/medoid-${{matrix.tree}}.fasta
        
  ########################################################################################        
         
  other-tests:
    name: adeno-fiber - other tests
    runs-on: [self-hosted, famsa]
    needs: medoid-tree
    strategy:
      fail-fast: false
      matrix:
        compiler: [9, 10, 11]
        
    env: 
      REF_DIR: ./test/adeno_fiber
      INPUT: ./test/adeno_fiber/adeno_fiber
 
    steps:       
    - name: export distance
      run: |
        ./famsa-${{matrix.compiler}} -dist_export ${INPUT} dist.csv
        cmp dist.csv ${REF_DIR}/dist.csv
        
    - name: export distance (square)
      run: |
        ./famsa-${{matrix.compiler}} -dist_export -square_matrix ${INPUT} dist_sq.csv
        cmp dist_sq.csv ${REF_DIR}/dist_sq.csv
        
    - name: export pid
      run: |
        ./famsa-${{matrix.compiler}} -dist_export -pid ${INPUT} pid.csv
        cmp pid.csv ${REF_DIR}/pid.csv
        
    - name: export pid (square)
      run: |
        ./famsa-${{matrix.compiler}} -dist_export -square_matrix -pid ${INPUT} pid_sq.csv
        cmp pid_sq.csv ${REF_DIR}/pid_sq.csv
      


